### ISSUE TITLE
feature (?) groups

### ISSUE THREAD

**Issue by whatSocks** [jointakahe/takahe#227]
I seem to be unable to interact with groups. 

Although the UI says I follow this group - https://takahe.social/@takahe@a.gup.pe/ , checking on the group's home page shows that the group has 0 followers https://a.gup.pe/u/takahe

**Comment by andrewgodwin** [comment]
Which user account did you try to follow it from? I'll look up the Follow object - it's probably still in pending state and the other end didn't accept for some reason.

**Comment by whatSocks** [comment]
just tried anew with applesauce@takahe.social

**Comment by andrewgodwin** [comment]
Looks like we successfully dispatched the Follow request so it's probably a problem with the other end not being able to pull our info for some reason. This will need more investigation!

**Comment by andrewgodwin** [comment]
I believe this is fixed on our end now - @whatSocks are you still running into this issue?

**Comment by whatSocks** [comment]
@andrewgodwin still getting follow pending here https://takahe.social/@takahe@a.gup.pe/

**Comment by andrewgodwin** [comment]
OK, then there's some pull failing at the other end, then. We'll need to get some more insight from someone on the other end to fix this one I suspect.
