### ISSUE TITLE
Crashes on login with Ivory, but works after re-opening

### ISSUE THREAD

**Issue by Ciantic** [jointakahe/takahe#473]
Crashes on login with Ivory, but works after re-opening the app.

I don't have a yet better report, but I noticed that GoToSocial has a similar issue:

https://github.com/superseriousbusiness/gotosocial/issues/1339

Which helpfully contains the list of requests Ivory does on login:

```
  /api/v1/timelines/home?limit=40
* /api/v1/accounts/1
* /api/v2/instance
* /api/v1/preferences
  /api/v1/timelines/home?limit=40&min_id=...
  /api/v1/lists
  /api/v1/accounts/1/statuses?exclude_reblogs=1&limit=40
  /api/v1/notifications? limit=100&since_id=...&types%5B%5D=mention&types%5B%5D=status&types%5B%5D=reblog&types%5B%5D=follow&types%5B%5D=follow_request&types%5B%5D=favourite&types%5B%5D=poll&types%5B%5D=update
  /api/v1/notifications?limit=30&types%5B%5D=mention
```

**Comment by andrewgodwin** [comment]
We don't support `/v2/instance` so my guess is that that's the culprit.

**Comment by andrewgodwin** [comment]
OK, I've implemented that endpoint to a reasonable standard, worth trying again.

**Comment by andrewgodwin** [comment]
Yup, with that implemented Ivory works straight away!

**Comment by Ciantic** [comment]
I tried with takahe.social, it still crashed there, maybe it's not yet updated there.

**Comment by andrewgodwin** [comment]
I just tried there (that's where I deployed the fix) and it worked perfectly first time?
